name: IVAS OTP Bot

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Libraries
        run: |
          pip install flask cloudscraper beautifulsoup4 brotli

      - name: Run Bot
  env:
    COOKIES_JSON: ${{ secrets.COOKIES_JSON }}
  run: |
    python app.py
